import { Inter } from "next/font/google";
import "./globals.css";
import Loading from "./loading";
import SingleInvoice from "./aboutinvoice/[id]/page";

import { Navbar,InvoicesList,StateButton  } from "@/components";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export const revalidate = 60

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
        <main className="max-w-6xl mx-auto">{children}</main>
  
      </body>
    </html>
  );
}
