import { Navbar, StateButton } from "@/components";
import InvoicesList from "@/components/InvoiceList";

export const metadata = {
  title: "Home ",
  description: "Generated by create next app",  
};

async function getData(url) {
  const req = await fetch(url , {
    next:{
      revalidate:60
    }
  })

  const data = await req.json()

  return data
  
}


async function Home() {
  const invoices = await  getData('http://localhost:4000/data') 
  console.log(invoices);
  return <main className="max-w-4xl mx-auto">
    <main className="max-w-6xl mx-auto">
      <Navbar/>
    </main>
    <InvoicesList invoices={invoices}/>
  </main> 
}

export default Home;
